spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:6006/smallgroup?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: rootroot
    
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

server:
  port: 80

file:
  upload-path : /Users/seoeunji/Library/Containers/com.linearity.vn/Data/Documents/6.spring_project/smallgroup/workspace/images/