spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://database-1.cma1tt2xener.ap-northeast-2.rds.amazonaws.com:3306/smallgroup?serverTimezone=UTC&characterEncoding=UTF-8
    username: admin
    password: ss2565226!
    
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

server:
  port: 80
  servlet:
    session:
      timeout: 60

file:
  window:
    upload-path : /Users/seoeunji/Library/Containers/com.linearity.vn/Data/Documents/6.spring_project/smallgroup/workspace/images
  linux:
    upload-path : /usr/works/images